AWSTemplateFormatVersion: '2010-09-09'
Description: 'TechTranslator - Simple CloudTrail Audit Logging'

Parameters:
  ProjectName:
    Type: String
    Default: TechTranslator
    Description: Name of the project
  DynamoDBStackName:
    Type: String
    Default: tech-translator-dynamodb
    Description: Name of the DynamoDB stack to audit

Resources:
  # Simple S3 bucket for CloudTrail logs
  CloudTrailLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-audit-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Simple bucket policy for CloudTrail
  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${CloudTrailLogsBucket.Arn}/*'
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt CloudTrailLogsBucket.Arn

  # CloudTrail for comprehensive microservice audit logging
  AuditTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: CloudTrailBucketPolicy
    Properties:
      TrailName: !Sub '${ProjectName}-audit'
      S3BucketName: !Ref CloudTrailLogsBucket
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: false
      EnableLogFileValidation: true
      EventSelectors:
        # Track all DynamoDB operations (data layer debugging)
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources:
            - Type: 'AWS::DynamoDB::Table'
              Values: 
                - !Sub 
                  - 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${VectorTable}'
                  - VectorTable:
                      Fn::ImportValue: !Sub '${DynamoDBStackName}-VectorStorageTableName'
                - !Sub
                  - 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ConversationTable}'
                  - ConversationTable:
                      Fn::ImportValue: !Sub '${DynamoDBStackName}-ConversationHistoryTableName'
            # Track Lambda invocations (service-to-service calls)
            - Type: 'AWS::Lambda::Function'
              Values: ['*']
            # Track S3 knowledge base access
            - Type: 'AWS::S3::Object'  
              Values: ['arn:aws:s3:::tech-translator-s3-knowledge-base/*']

Outputs:
  CloudTrailArn:
    Description: CloudTrail ARN for audit logging
    Value: !GetAtt AuditTrail.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailArn'

  AuditBucket:
    Description: S3 bucket with audit logs
    Value: !Ref CloudTrailLogsBucket
    Export:
      Name: !Sub '${AWS::StackName}-AuditBucket'

  GovernanceImplemented:
    Description: Governance features
    Value: 'CloudTrail audit logging, DynamoDB data events, S3 encrypted storage'