AWSTemplateFormatVersion: '2010-09-09'
Description: 'TechTranslator - CloudWatch Monitoring with SageMaker Integration'

Parameters:
  ProjectName:
    Type: String
    Default: TechTranslator
    Description: Name of the project
  LambdaStackName:
    Type: String
    Default: tech-translator-lambda
    Description: Name of the Lambda stack
  ApiStackName:
    Type: String
    Default: tech-translator-api
    Description: Name of the API Gateway stack
  DynamoDBStackName:
    Type: String
    Default: tech-translator-dynamodb
    Description: Name of the DynamoDB stack
  SageMakerEndpointName:
    Type: String
    Description: Name of your deployed SageMaker endpoint
    Default: "NOT_CONFIGURED"

Conditions:
  HasSageMakerEndpoint: !Not [!Equals [!Ref SageMakerEndpointName, "NOT_CONFIGURED"]]

Resources:
  TechTranslatorDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-Dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Duration", "FunctionName", "${LambdaStackName}-main" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Invocations", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Performance",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ApiGateway", "Count", "ApiName", "${ProjectName}-api" ],
                  [ ".", "Latency", ".", "." ],
                  [ ".", "4XXError", ".", "." ],
                  [ ".", "5XXError", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "API Gateway Metrics",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 24,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${DynamoDBStackName}-vector-storage" ],
                  [ ".", "ConsumedWriteCapacityUnits", ".", "." ],
                  [ ".", "ConsumedReadCapacityUnits", "TableName", "${DynamoDBStackName}-conversation-history" ],
                  [ ".", "ConsumedWriteCapacityUnits", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "DynamoDB Usage",
                "period": 300
              }
            }${SageMakerWidget}
          ]
        }

  # Add conditional SageMaker widget
  SageMakerWidget: !If
    - HasSageMakerEndpoint
    - !Sub |
        ,
        {
          "type": "metric",
          "x": 0,
          "y": 12,
          "width": 24,
          "height": 6,
          "properties": {
            "metrics": [
              [ "AWS/SageMaker", "Invocations", "EndpointName", "${SageMakerEndpointName}" ],
              [ ".", "ModelLatency", ".", "." ],
              [ ".", "OverheadLatency", ".", "." ]
            ],
            "view": "timeSeries",
            "stacked": false,
            "region": "${AWS::Region}",
            "title": "SageMaker Endpoint Performance",
            "period": 300
          }
        }
    - ""