AWSTemplateFormatVersion: '2010-09-09'
Description: 'TechTranslator - S3 Resources for Website and Knowledge Base'

Parameters:
  ProjectName:
    Type: String
    Default: TechTranslator
    Description: Name of the project, used as prefix for resource names

Resources:
  # Frontend Website Bucket
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-website'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET]
            AllowedOrigins: ['*']
            MaxAge: 3000
      Tags:
        - Key: Project
          Value: !Ref ProjectName
  
  # Website Bucket Policy
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadAccess
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${WebsiteBucket.Arn}/*'
          - Sid: AllowLabRoleAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LabRole'
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource: 
              - !Sub '${WebsiteBucket.Arn}'
              - !Sub '${WebsiteBucket.Arn}/*'
  
  # Knowledge Base Bucket
  KnowledgeBaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-knowledge-base'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Project
          Value: !Ref ProjectName
  
  # Knowledge Base Bucket Policy
  KnowledgeBaseBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KnowledgeBaseBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowLabRoleAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LabRole'
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource: 
              - !Sub '${KnowledgeBaseBucket.Arn}'
              - !Sub '${KnowledgeBaseBucket.Arn}/*'

Outputs:
  WebsiteBucketName:
    Description: Name of the website bucket
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketName'
  
  WebsiteBucketArn:
    Description: ARN of the website bucket
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketArn'
  
  WebsiteBucketUrl:
    Description: URL of the website
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketUrl'
  
  WebsiteBucketRegionalDomainName:
    Description: Regional domain name of the website bucket
    Value: !GetAtt WebsiteBucket.RegionalDomainName
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketRegionalDomainName'
  
  KnowledgeBaseBucketName:
    Description: Name of the knowledge base bucket
    Value: !Ref KnowledgeBaseBucket
    Export:
      Name: !Sub '${AWS::StackName}-KnowledgeBaseBucketName'
  
  KnowledgeBaseBucketArn:
    Description: ARN of the knowledge base bucket
    Value: !GetAtt KnowledgeBaseBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-KnowledgeBaseBucketArn'