AWSTemplateFormatVersion: '2010-09-09'
Description: 'TechTranslator - Simple WAF Protection'

Parameters:
  ProjectName:
    Type: String
    Default: TechTranslator
    Description: Name of the project
  ApiStackName:
    Type: String
    Default: tech-translator-api
    Description: Name of the API Gateway stack

Resources:
  # Simple WAF with managed rules
  TechTranslatorWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${ProjectName}-WebACL'
      Description: 'Basic WAF protection for TechTranslator API'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      # REQUIRED: Top-level VisibilityConfig for the WebACL itself
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${ProjectName}WebACL'
      Rules:
        # Rate limiting (most important for your use case)
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
        
        # AWS Managed Core Rule Set (protects against common attacks)
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRuleSet
            
        # Known bad inputs rule set
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: KnownBadInputs

  # Associate WAF with your API Gateway
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Sub 
        - 'arn:aws:apigateway:${AWS::Region}::/restapis/${ApiId}/stages/v1'
        - ApiId:
            Fn::ImportValue: !Sub '${ApiStackName}-ApiGatewayId'
      WebACLArn: !GetAtt TechTranslatorWebACL.Arn

Outputs:
  WebACLArn:
    Description: ARN of the WAF Web ACL
    Value: !GetAtt TechTranslatorWebACL.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebACLArn'

  SecurityProtection:
    Description: WAF protection implemented
    Value: 'Rate limiting (2000 req/5min), Common attack protection, Known bad inputs blocking'
    Export:
      Name: !Sub '${AWS::StackName}-Protection'